name: ART UI Branch
on:
  push:
    branches-ignore:
      - main
jobs:
  flutter-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
      - run: flutter pub get
      - run: flutter test
